name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  basic-build:
    name: Basic Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '24'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        run: ./mvnw --batch-mode --no-transfer-progress clean verify

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Test CLI commands (basic)
        run: |
          JAR_FILE="./target/setup-${{ steps.get_version.outputs.VERSION }}.jar"
          echo "Testing basic CLI functionality with $JAR_FILE"
          
          # Test help commands
          java -jar $JAR_FILE --help
          java -jar $JAR_FILE init --help
          
          # Test cursor functionality with different parameter counts
          echo "Testing 1-parameter cursor:"
          java -jar $JAR_FILE init --cursor https://github.com/jabrena/cursor-rules-java
          
          echo "Testing 2-parameter cursor:"
          java -jar $JAR_FILE init --cursor https://github.com/jabrena/cursor-rules-agile ./cursor/rules
          
          echo "Testing 3-parameter cursor:"
          java -jar $JAR_FILE init --cursor https://github.com/jabrena/cursor-rules-java ./cursor/rules ./my-custom-rules
          
          # Test other basic functionality
          java -jar $JAR_FILE init --editorconfig
          java -jar $JAR_FILE init --sdkman
          java -jar $JAR_FILE init --gitignore
          
          echo "✅ Basic CLI functionality verified"

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup-${{ steps.get_version.outputs.VERSION }}.jar
          path: ./target/setup-${{ steps.get_version.outputs.VERSION }}.jar
          retention-days: 7

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            ./target/surefire-reports
            ./target/site
          retention-days: 7